### ISSUE TITLE
Lmk2Bbox_7lmks NOT FOUND in the PXPtxs.py 

### ISSUE THREAD

**Issue by ytoon** [xipeng13/recurrent-face-alignment#2]
Hi, I found a error in the code.  The **Lmk2Bbox_7lmks** was in the PXTrack.py not in the PXPts.py.
But in all *Demo.py, you use the  **PXPTs.Lmk2Bbox_7lmks** to call the function. It's a fault.

**Comment by xipeng13** [comment]
Thanks, it is solved. Update PXPTs.py and remove PXTrack.py.
